# Generated by Django 4.2.9 on 2024-05-04 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='logindatabase',
            new_name='signupdatabase',
        ),
    ]
