# Generated by Django 4.2.9 on 2024-05-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanagement', '0002_rename_logindatabase_signupdatabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='department1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeename', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='signupdatabase',
            name='id',
        ),
        migrations.AlterField(
            model_name='signupdatabase',
            name='password',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, unique=True),
        ),
    ]
