# Generated by Django 4.2.9 on 2024-05-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanagement', '0005_profileimagedb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profileimagedb',
        ),
    ]
