# Generated by Django 4.2.9 on 2024-05-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanagement', '0007_perfomancedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='trainingdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training', models.CharField(max_length=128)),
                ('trainingdate', models.DateField()),
            ],
        ),
    ]
